cache:
  untracked: true

stages:
  - clean
  - pack
  - copy

cleanup:
  stage: clean
  script:
    - rm -f /var/www/html/download/jazztronauts/*

package:
  stage: pack
  script: 
    - 7z a build ./gamemodes

update:
  stage: copy
  script:
    - today=`date '+%Y_%m_%d__%H_%M_%S'`
    - cp -f build.7z /var/www/html/download/jazztronauts/jazztronauts$today.7z