stages:
  - addon

makeaddon:
  stage: addon
  tags: [steam]
  script:
    - whoami
    - cwd=$(pwd)
    - msg=$(git log -1 --pretty=%B)
    - cp -rf gamemodes/shoot/content/* .
    - rm -rf gamemodes/shoot/content/
    - mv gamemodes/shoot/addon.json addon.json
    - mv gamemodes/shoot/shoot_icon.jpg shoot_icon.jpg
    - cd /home/steam/server/bin/
    - LD_LIBRARY_PATH=./ ./gmad_linux create -folder "$cwd" -out "$cwd/shoot.gma"
    - LD_LIBRARY_PATH=./ ./gmpublish_linux update -addon "$cwd/shoot.gma" -id "1325059434" -changes "$msg"